# Testing on linux, windows, macos, for python versions 3.8, 3.9, 3.10, 3.11, 3.12
# Note: Python 3.7 support was dropped as it reached End of Life (EOL) on June 27, 2023

name: Test pip install

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Version check
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "Cython>=0.29.23" "coveralls"
      - name: Install package
        run: |
          pip install build
          python -m build --sdist
          python -c "import glob, subprocess, sys; files = glob.glob('dist/*.tar.gz'); assert files, 'No .tar.gz files found in dist/'; subprocess.check_call([sys.executable, '-m', 'pip', 'install'] + files)"
